# Generated by Django 2.0.7 on 2019-12-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=32)),
                ('EMAIL', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=10)),
            ],
        ),
    ]
