# Generated by Django 2.0.7 on 2019-12-23 11:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='otime',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 23, 11, 19, 18, 155184, tzinfo=utc)),
        ),
    ]
