# Generated by Django 2.0.7 on 2019-12-23 11:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_checkout_otime'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='itime',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 23, 11, 24, 58, 299794, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='otime',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 23, 11, 24, 58, 299794, tzinfo=utc)),
        ),
    ]
