# Generated by Django 2.0.7 on 2019-12-23 12:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20191223_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='itime',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 23, 12, 3, 7, 525236, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='otime',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 23, 12, 3, 7, 525236, tzinfo=utc)),
        ),
    ]
