# Generated by Django 3.0 on 2020-01-04 18:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20191223_1733'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='host',
            name='Pswd',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='Phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='itime',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 4, 18, 4, 3, 589282, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='Phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='otime',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 4, 18, 4, 3, 589282, tzinfo=utc)),
        ),
    ]
