# Generated by Django 3.0 on 2020-01-04 18:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20200104_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='Phone',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='itime',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 4, 18, 19, 14, 436171, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='Phone',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='otime',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 4, 18, 19, 14, 440171, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='host',
            name='Phone',
            field=models.CharField(max_length=13),
        ),
    ]
