# Generated by Django 3.0 on 2020-01-05 08:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20200105_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='itime',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 5, 8, 46, 40, 875649, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='otime',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 5, 8, 46, 40, 876648, tzinfo=utc)),
        ),
    ]
