# Generated by Django 3.0 on 2020-01-05 09:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_auto_20200105_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='itime',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 5, 9, 47, 24, 737428, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='otime',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 5, 9, 47, 24, 738428, tzinfo=utc)),
        ),
        migrations.AlterModelTable(
            name='host',
            table=None,
        ),
    ]
