# Generated by Django 3.0 on 2020-01-06 11:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_auto_20200106_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone', models.CharField(max_length=13)),
                ('otime', models.DateTimeField(default=datetime.datetime(2020, 1, 6, 11, 52, 50, 168777, tzinfo=utc))),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='itime',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 6, 11, 52, 50, 162684, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='itime',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 6, 11, 52, 50, 165214, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='otime',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 6, 11, 52, 50, 167244, tzinfo=utc)),
        ),
    ]
