# Generated by Django 3.0 on 2020-01-06 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_auto_20200106_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='itime',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 6, 17, 31, 25, 16859)),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='otime',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 6, 17, 31, 25, 16859)),
        ),
        migrations.AlterField(
            model_name='exit',
            name='otime',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 6, 17, 31, 25, 18882)),
        ),
        migrations.AlterField(
            model_name='host',
            name='itime',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 6, 17, 31, 25, 13307)),
        ),
    ]
