# Generated by Django 3.0 on 2020-01-06 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0035_auto_20200106_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone', models.CharField(default='', max_length=13, null=True)),
                ('Pswd', models.CharField(default='', max_length=32)),
                ('otime', models.DateTimeField(default=datetime.datetime(2020, 1, 6, 22, 32, 20, 190305))),
            ],
        ),
        migrations.DeleteModel(
            name='Exit',
        ),
        migrations.AlterField(
            model_name='checkin',
            name='itime',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 6, 22, 32, 20, 190305)),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='otime',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 6, 22, 32, 20, 190305)),
        ),
        migrations.AlterField(
            model_name='host',
            name='itime',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 6, 22, 32, 20, 186240)),
        ),
    ]
